# Generated by Django 4.0.4 on 2022-04-24 05:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodinward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('rate', models.FloatField(max_length=100, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('price', models.FloatField(max_length=100, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('discount', models.FloatField(blank=True, default=0, max_length=100, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('gst', models.FloatField(blank=True, default=0, max_length=100, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('sgst', models.FloatField(blank=True, default=0, max_length=100, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('is_billed', models.BooleanField(default=False)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
            ],
        ),
    ]
