# Generated by Django 4.0.4 on 2022-04-23 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('dob', models.CharField(max_length=50)),
                ('doj', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('flat_no', models.CharField(max_length=15)),
                ('st_name', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, default='default.jpg', upload_to='photos')),
                ('doc', models.FileField(default='', upload_to='documents')),
                ('salary', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
            ],
        ),
    ]
