# Generated by Django 4.0.4 on 2022-04-24 05:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodinward', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inward_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('products', models.ManyToManyField(related_name='inward_purchase_bill', to='prodinward.prodinward')),
                ('sup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='supplier.suppliers')),
            ],
        ),
    ]
