# Generated by Django 4.0.4 on 2022-04-24 09:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('remark', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss', to='product.product')),
            ],
        ),
    ]
